---
title: "iPSC Motor Neurons and Spinal Cord Cell Refs Data"
author: "Jenny L Smith"
date: "`R Sys.Date()`"
output: html_document
---

# Set-up 

```{r set-up, echo=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80),
                      tidy=TRUE,
                      fig.align='center',
                      fig.width = 10, fig.height = 10,
                      eval = TRUE)

options(stringsAsFactors = FALSE, max.print = 100)
table = function (..., useNA = 'ifany') base::table(..., useNA = useNA)
```

```{r message=FALSE,warning=FALSE}
library(dplyr)
library(tidyr)
library(magrittr)
library(stringr)
library(ggplot2)
library(tibble)

library(Seurat)
library(SeuratDisk)


library(RColorBrewer)
```

```{r}
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter","dplyr")
conflicted::conflict_prefer("saveRDS","base")
```

# Parallelization 

```{r}
library(future)
# check the current active plan
plan()
```

```{r}
plan("multisession", workers = 16)
plan()
options(future.globals.maxSize = 60000 * 1024^2)
```


# Genome Refs

```{r eval=FALSE}
suppressPackageStartupMessages(library(ensembldb))

db <- ensDbFromGtf("resources/genome/Homo_sapiens.GRCh38.109.chr.gtf.gz")
```

```{r}
edb <- ensembldb::EnsDb("resources/genome/Homo_sapiens.GRCh38.109.sqlite")

edb
```

```{r}
gids <- ensembldb::keys(edb, keytype = "GENEID")

idmap <- AnnotationDbi::select(edb, keytype="GENEID", 
                      keys = gids, 
                      columns = c("GENEID","GENEBIOTYPE","GENENAME","SYMBOL")) %>% 
  janitor::clean_names()

head(idmap)
```

# Reference Data Set(s)

1. https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE136719
2. https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE138121
3. https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE171892
3-1. https://juliendelile.github.io/Antler/
3-2. https://shiny.crick.ac.uk/scviewer/neuraltube/

4. Yadav 2023 
  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE190442
  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE222322

```{r eval=FALSE}
library(GEOQuery)

gse <- getGEO("GSE190442", GSEMatrix=FALSE)

head(Meta(gse))
names(GSMList(gse))
```



# Session Info

```{r}
session_info()
```

